name: uix_dbmon
version: 0.0.1
description: "DBMonster benchmark app: uix library."
author: Boris Kaul <localvoid@gmail.com>
homepage: https://github.com/localvoid/uix_dbmon
environment:
  sdk: '>=1.9.0-dev'
dependencies:
  browser: any
  uix: any
transformers:
- $dart2js:
    checked: false
    minify: true
    commandLineOptions: ['--trust-type-annotations', '--trust-primitives']